[theme]

# Primary accent for interactive elements
primaryColor = '#FFA500' 

# Background color for the main content area
backgroundColor = '#001E3C'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#152D4D'

# Color used for almost all text
textColor = '#E0E0E0'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"